# backend/app/mock_data.py
from datetime import datetime

# Mock data for active disputes
ACTIVE_DISPUTES = [
    {
        "id": 1,
        "type": "Unauthorized Transaction",
        "amount": 500,
        "status": "High Risk",
        "timeRemaining": "1h 45m",
        "riskScore": 85,
        "description": "User claims transaction was not authorized",
        "patterns": ["Multiple failed attempts", "New device", "Unusual amount"],
        "buyer": {
            "username": "john_doe",
            "accountAge": "2 years",
            "previousDisputes": 0,
            "riskScore": "Low",
            "verifiedStatus": True,
        },
        "seller": {
            "username": "jane_smith",
            "accountAge": "1 year",
            "previousDisputes": 1,
            "riskScore": "Medium",
            "verifiedStatus": False,
        },
        "evidence": [
            {
                "id": 1,
                "type": "Bank Transfer PDF",
                "submittedAt": "2023-07-20 14:35",
                "verified": True,
                "documentUrl": "/document.pdf",
                "videoUrl": "/video.mp4",
                "pendingParty": None,
                "verificationDetails": "Document verified with bank records",
            },
            {
                "id": 2,
                "type": "Pending Evidence",
                "submittedAt": None,
                "verified": False,
                "documentUrl": None,
                "videoUrl": None,
                "pendingParty": "seller",
                "verificationDetails": "Awaiting submission",
            },
        ],
        "createdAt": "2023-07-20 14:30",
        "deadline": "2023-07-21 14:30",
    },
    {
        "id": 2,
        "type": "Non-receipt of Goods",
        "amount": 250,
        "status": "Medium Risk",
        "timeRemaining": "1h 30m",
        "riskScore": 65,
        "description": "Buyer hasn't received the item",
        "patterns": ["First-time seller", "No tracking provided"],
        "buyer": {
            "username": "sarah_parker",
            "accountAge": "3 years",
            "previousDisputes": 1,
            "riskScore": "Low",
            "verifiedStatus": True,
        },
        "seller": {
            "username": "new_seller123",
            "accountAge": "1 month",
            "previousDisputes": 0,
            "riskScore": "High",
            "verifiedStatus": False,
        },
        "evidence": [],
        "createdAt": "2023-07-20 15:00",
        "deadline": "2023-07-21 15:00",
    },
]

# Mock data for AI-resolved disputes
AI_RESOLVED_DISPUTES = [
    {
        "id": "D123456",
        "type": "Buyer Underpaid",
        "amount": 500.0,
        "resolution": "Auto-resolved",
        "closedAt": "2023-07-20 15:30",
        "aiConfidenceScore": 98,
        "patternMatch": "Clear underpayment pattern",
        "resolvedAt": "2023-07-20 15:31",
        "resolutionConfidence": 98,
        "buyer": {
            "username": "michael_b",
            "accountAge": "4 years",
            "previousDisputes": 0,
            "riskScore": "Low",
            "verifiedStatus": True,
        },
        "seller": {
            "username": "tech_store",
            "accountAge": "5 years",
            "previousDisputes": 2,
            "riskScore": "Low",
            "verifiedStatus": True,
        },
        "aiAnalysis": {
            "conclusion": "Clear underpayment case",
            "evidenceVerified": True,
            "fraudChecks": {
                "documentAuthenticity": "Verified",
                "transactionMatch": "Confirmed",
                "patternAnalysis": "No suspicious patterns",
            },
            "resolutionDetails": "Seller refunded difference automatically",
            "timeToResolve": "45 seconds",
        },
        "evidence": [
            {
                "id": 1,
                "type": "Payment Receipt",
                "submittedAt": "2023-07-20 15:30",
                "verified": True,
                "verificationDetails": "Document verified through blockchain",
                "url": "/receipt.pdf",
            },
        ],
        "createdAt": "2023-07-20 15:30",
    },
    {
        "id": "D123457",
        "type": "Buyer Overpaid",
        "amount": 1200.0,
        "resolution": "Auto-refunded",
        "closedAt": "2023-07-20 16:45",
        "aiConfidenceScore": 99,
        "patternMatch": "System calculation error",
        "resolvedAt": "2023-07-20 16:46",
        "resolutionConfidence": 99,
        "buyer": {
            "username": "emma_w",
            "accountAge": "2 years",
            "previousDisputes": 1,
            "riskScore": "Low",
            "verifiedStatus": True,
        },
        "seller": {
            "username": "global_shop",
            "accountAge": "3 years",
            "previousDisputes": 0,
            "riskScore": "Low",
            "verifiedStatus": True,
        },
        "aiAnalysis": {
            "conclusion": "Verified overpayment",
            "evidenceVerified": True,
            "fraudChecks": {
                "documentAuthenticity": "Verified",
                "transactionMatch": "Confirmed",
                "patternAnalysis": "Normal transaction pattern",
            },
            "resolutionDetails": "Excess amount automatically refunded to buyer",
            "timeToResolve": "30 seconds",
        },
        "evidence": [
            {
                "id": 1,
                "type": "Transaction Log",
                "submittedAt": "2023-07-20 16:45",
                "verified": True,
                "verificationDetails": "System log verified",
                "url": "/transaction.pdf",
            },
        ],
        "createdAt": "2023-07-20 16:45",
    },
]